"""Fresh saved-evidence acceptance, with explicit recomputation boundaries."""
from pathlib import Path
import argparse,hashlib,json,shutil,subprocess,sys,tempfile,re
ROOT=Path(__file__).resolve().parent
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def verify(root):
    data=json.loads((root/'SCIENTIFIC-MANIFEST.json').read_text(encoding='utf8'))
    for row in data['files']:
        p=root/row['path'];assert p.resolve().is_relative_to(root.resolve()) and p.is_file(),row['path']
        assert p.stat().st_size==row['bytes'] and sha(p)==row['sha256'],row['path']
    return data
def main():
    p=argparse.ArgumentParser();p.add_argument('--full',action='store_true');p.add_argument('--manifest-only',action='store_true');a=p.parse_args()
    data=verify(ROOT)
    if a.manifest_only:print('PASS immutable scientific inputs',len(data['files']));return
    work=Path(tempfile.mkdtemp(prefix='verification-',dir=ROOT))
    assert work.resolve().is_relative_to(ROOT.resolve()) and work!=ROOT
    for row in data['files']:
        target=work/row['path'];target.parent.mkdir(parents=True,exist_ok=True);shutil.copyfile(ROOT/row['path'],target)
    shutil.copyfile(ROOT/'SCIENTIFIC-MANIFEST.json',work/'SCIENTIFIC-MANIFEST.json')
    for nt in [1024,2048]:
        for cache in (work/f'new-research/experiments/N{nt}').glob('point-independent-*.json'):
            assert cache.resolve().is_relative_to(work.resolve());cache.unlink()
    steps=[('baseline/heston-frontier-20261007/run_frontier.py',['--full'] if a.full else []),
        ('new-research/theory/rho-direct-check.py',[]),('new-research/theory/rho-direct-controls.py',[]),
        ('new-research/experiments/run_experiments.py',[]),
        ('v3/kernel/independent.py',['--baseline',str(work)]),
        ('v3/audit-experiments/read_audit_independent.py',['--baseline',str(work)]),
        ('v3/extensions/check_appendices.py',[])]
    record={'status':'RUNNING','tested_scientific_manifest_sha256':sha(ROOT/'SCIENTIFIC-MANIFEST.json'),'driver_sha256':sha(Path(__file__)),'full':a.full,'steps':[],
        'scope':'Fresh-copy saved-evidence acceptance, strict price/objective/output reconstruction, full new kernel-weight algebra and semantic negative controls. Full adds the original 211241 structural-sign leaves. Every continuous residual derivative is not regenerated by either mode.',
        'independence':'Author-side execution. Kernel cumulative algebra and audit assembly have separate readers; strict elementary primitives and saved continuous derivative validity remain shared. Not external referee reproduction.'}
    receipt=ROOT/'FRESH-ACCEPTANCE.json'
    receipt.write_text(json.dumps(record,indent=2)+'\n',encoding='utf8')
    for script,args in steps:
        run=subprocess.run([sys.executable,'-X','utf8','-B',str(work/script),*args],capture_output=True,text=True,encoding='utf8')
        output=(run.stdout+run.stderr).replace(str(work),'<verification-copy>').replace(str(ROOT),'<evidence>')
        output=re.sub(r'[A-Za-z]:[\\/]Users[\\/][^\r\n"\']+','<local-path>',output)
        safe_args=[('<verification-copy>' if x==str(work) else x) for x in args]
        record['steps'].append({'script':script,'args':safe_args,'source_sha256':sha(work/script),'returncode':run.returncode,'output':output})
        if run.returncode:
            record['status']='FAILED';receipt.write_text(json.dumps(record,indent=2)+'\n',encoding='utf8');print('FAIL',script,flush=True);raise SystemExit(run.returncode)
        receipt.write_text(json.dumps(record,indent=2)+'\n',encoding='utf8')
        print('PASS',script,flush=True)
    verify(ROOT);record['status']='PASS_FRESH_COMPLETE_SCIENTIFIC_ACCEPTANCE';record['scientific_input_objects']=len(data['files'])
    receipt.write_text(json.dumps(record,indent=2)+'\n',encoding='utf8');print(record['status'],flush=True)
if __name__=='__main__':main()
